name: 'CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: yarn --frozen-lockfile

      - name: 'Build'
        run: yarn build

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: yarn --frozen-lockfile

      - name: 'Test'
        run: yarn check-types # TODO: add tests

  semantic-release:
    name: 'Release'
    runs-on: ubuntu-latest
    needs: ['test', 'build']
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: yarn --frozen-lockfile

      - name: 'Build package'
        run: yarn build

      - name: 'Release'
        id: 'release'
        uses: codfish/semantic-release-action@v2.2.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # expires 13May24

  gen-contributors:
    name: 'Generate Contributors List'
    runs-on: ubuntu-latest
    needs: ['test', 'build', 'semantic-release']
    if: github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          image_size: 100
          columns_per_row: 8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
